/* Eleven presentation scenes. Holds are speaking beats inside a scene, not pages. */
(function () {
  const opening = [
    {id:'TITLE',label:'Enlace',time:.8,note:'Let the Enlace name register. Then begin the familiar exchange pattern.'},
    {id:'H01',label:'Airbnb',time:6.35,note:'Airbnb makes spare rooms available to travelers. The familiar idea is that existing resources become available for exchange.'},
    {id:'H02',label:'Uber',time:11.9,note:'Uber does this with driver availability and ride requests, continuously. These are familiar examples, with their own operational and pricing constraints.'},
    {id:'H03',label:'Enlace',time:26.95,note:'Enlace brings a decision and pricing layer to logistics exchanges across independent companies. Here A’s six positions split between B and C. C also receives one from D. Every offered unit is accounted for. This is an illustrative allocation, not customer data. Our first product applies this principle inside private shipper networks, using their existing carriers.'},
  ];
  const scenes = [{id:'S01',number:1,label:'Airbnb → Uber → Enlace',chapter:'Opening',start:0,end:26.95,holds:opening}];
  function scene(id,label,chapter,duration,beats,note,source='') {
    const start=Number((scenes.at(-1).end+.05).toFixed(2));
    const item={id,number:scenes.length+1,label,chapter,start,end:Number((start+duration).toFixed(2)),note,source};
    item.holds=beats.map(([offset,beatLabel,beatNote],i)=>({id:id+'-'+(i+1),label:beatLabel,time:Number((start+offset).toFixed(2)),note:beatNote||note}));
    scenes.push(item);
  }
  scene('S02','Unused resources across logistics','The problem',21,[[8,'Truck: loaded outbound, empty return'],[15,'Containers: surplus and shortage ports'],[21,'Separate organizations, separate resources']],
    'This problem appears across logistics. In 2024, 21.6% of EU road-freight vehicle-km were travelled empty (Eurostat). The journey is illustrative; the figure does not measure return trips alone. A European Commission NMP study using 2021–22 data reports an average urban freight vehicle load factor of about 50% across 21 major European cities (Cartolano et al., 2025). Empty containers accumulate at surplus ports and must be repositioned to deficit ports. JMSE (2026) cites an industry estimate of $15–20 billion annually and a historical estimate of about 20% of ocean-container movements involving empties; neither is presented as a new 2026 measurement. These metrics have different scopes and cannot be added or treated as Enlace-addressable savings. The common coordination problem is that resources and demand sit across separate companies and networks, with distinct constraints and rules. Not all empty movements can be solved by exchanges. Warehouses and ships appear in the final visual without additional statistics.');
  scene('S03','Enlace clears the market.','The product',24,[[5,'Participants submit supply and demand'],[12,'Enlace evaluates the market rules and constraints'],[24,'Capacity is allocated with prices and terms']],
    'Enlace provides the market mechanism for a private logistics market. Participants submit supply and demand, together with operational and contractual constraints. The market operator defines the rules. Enlace combines mathematical optimization and market design to clear the market: determining which transactions occur, what quantity, at what price and on what terms. In this illustrative animation, Carrier A offers four units and Carrier D two; Shippers B and C each request three. A supplies three units to B and one to C, while D supplies two to C. A candidate connection from D to B fails the constraint check. All six units retain their source colors. Euro-and-check marks represent prices and terms returned with the allocation, without asserting actual prices or customer results. Transport capacity is the initial example.');
  scene('S04','Who pays and why','The customer',9,[[2,'Four buyers and their economic incentives'],[9,'Each runs its own logistics market']],
    'Different organizations can create an Enlace market, but they pay for different reasons. A company wants to reduce logistics cost. A 3PL can create a new service and monetize it. A consortium creates savings for its members. A public or infrastructure operator wants better use of capacity across its ecosystem. In every case, Enlace provides the market mechanism that lets the operator run that market. These are potential buyer categories and incentives, not claims of four validated customer segments. The initial go-to-market remains the design-partner market with two to three shippers.');
  scene('S11','Competition','Competition',8,[[8,'Who controls each network?']],
    'The comparison is about who controls the exchange environment. Amazon Flex focuses on Amazon deliveries. Uber Freight and Transporeon support freight management. Enlace is designed for a customer-defined logistics market where the operator controls participation, rules and the exchange mechanism. This is simplified public positioning, not an exhaustive feature audit.');
  scene('S06','Go to market','Go to market',15,[[2,'Agreed to start with a design partner'],[8,'Now: two to three shippers and their carriers'],[15,'Expand the market']],
    'We have agreed to start working with a design partner. We are now scoping the first market around two to three shippers with compatible freight lanes and their existing carriers. The goal is to prove repeatable capacity exchanges. Then we expand the market: more clients, more lanes, more participants and more resource types, opening new markets. The initial scope does not imply that all shippers are signed or live.');
  scene('S05','Business model','Business model',8,[[2.5,'A €200k+ annual starting point'],[8,'Expand revenue with market scope']],
    'The proposed recurring platform model starts at €200,000 or more per year for a private logistics market. The fee grows with the number of participants and the number and type of resources coordinated. Deployment and integration are additional one-time work. The initial scope is transport capacity across a small group of shippers. The proposed fee is not contracted revenue. Possible later usage fees are in the appendix.');
  scene('S07','Global market','Market context',8,[[2.5,'Global road freight'],[8,'Global logistics costs']],
    'The global economic context is $3.8 trillion in road freight and $12.29 trillion in logistics costs in 2024. Logistics costs are estimated by Armstrong & Associates; road freight is a Frost & Sullivan estimate cited in an HKEX filing. These estimates use separate methodologies. The appendix sizes platform revenue from market count times annual fee.',
    '2024 estimates · Armstrong & Associates; Frost & Sullivan / HKEX');
  scene('S08','Team','Team',6,[[6,'Founder expertise']],
    'Nathalia Wolf, CEO and co-founder: logistics and optimization, PhD in computer science and MSc Industrial Engineering. Juan Sepúlveda, CTO and co-founder: market design and optimization, PhD in computer science and MSc Electrical Engineering. Supported by Inria.');
  scene('S10','€2M Seed','The ask',6,[[2.5,'Roadmap'],[6,'From working technology to repeatable markets']],
    'We are seeking €2M in seed funding for a 24-month runway covering productization, deployment and commercial validation. Core technology is complete. First live markets are in progress with design partners. Company creation is planned for March 2027. The funding is intended to produce repeatable deployment across multiple paying markets and validate willingness to pay. Multiple paying markets is the intended outcome, not a claim of current revenue.');
  scene('S09','Vision','Closing',6,[[6,'Infrastructure for logistics markets']],
    'Transport capacity is the first resource. The ambition is an Enlace decision and pricing layer supporting exchanges across logistics resources. Close: Enlace provides infrastructure for logistics markets. Stop here and invite discussion.');

  const table=(head,rows)=>`<table class="appendix-table"><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
  const competitionTable=()=>table(['','Amazon Flex','Uber Freight','Transporeon','<span class="enlace-inline">Enlace</span>'],[
    ['Core purpose','Amazon deliveries','Freight management','Transport management','Logistics exchanges'],
    ['Procurement','No','Yes','Yes','Yes'],
    ['Multi-shipper sharing','No','Yes','Unconfirmed','Yes'],
    ['Participation control','Amazon','Uber Freight','Shipper','Network owner'],
    ['Rule definition','Amazon','Shipper + platform','Shipper + platform','Network owner'],
    ['Orchestrator','Amazon','Uber Freight','Shipper','Customer'],
    ['Own exchange network','No','No','Partial','Yes'],
    ['Resources','<span class="comparison-emoji" role="img" aria-label="Last-mile delivery capacity">🚗</span>','<span class="comparison-emoji" role="img" aria-label="Road and intermodal freight capacity">🚛 🚆</span>','<span class="comparison-emoji" role="img" aria-label="Transportation capacity">🚛</span>','<span class="comparison-emoji" role="img" aria-label="Transport, warehouses, shipping and containers">🚛🏭🚢📦</span>']
  ]).replace('class="appendix-table"','class="appendix-table comparison-table"');
  window.ENLACE_COMPETITION_TABLE=competitionTable();
  const note=text=>`<p class="appendix-foot">${text}</p>`;
  const grid=rows=>`<div class="appendix-grid">${rows.map(([a,b])=>`<div><h2>${a}</h2><p>${b}</p></div>`).join('')}</div>`;
  const appendix = [
    {id:'A09',label:'Participant value',headline:'Why would the other participants join?',html:grid([['Offering shipper','Recover value from capacity already paid for.'],['Requesting shipper','Access capacity without another dedicated move.'],['Carrier','Carry more on existing routes, within operational limits.']])+note('Participation depends on operational fit, compensation and permissions.'),note:'The offering company recovers value from capacity it cannot use. The requesting company accesses capacity without buying another dedicated movement. The carrier can carry more volume within an existing route, subject to operational fit and compensation. These are the benefits the first deployment must validate.'},
    {id:'A01',label:'Market-size methodology',headline:'Network count × starting annual fee.',
      html:table(['Private networks','Annual fee from','Platform ARR floor'],[[50,'€200k+','€10M+'],[100,'€200k+','€20M+'],[250,'€200k+','€50M+'],[500,'€200k+','€100M+']])+note('Illustrative scenarios. Excludes expansion, deployment and any usage-based revenue.'),
      note:'These are arithmetic scenarios, not a forecast, pipeline or a claim that the whole market is addressable. The €200k starting fee comes from the proposed commercial model. Qualified buyers, attainable network count, willingness to pay and deployment costs still need validation.'},
    {id:'A02',label:'Pricing model',headline:'Platform fee, expansion and deployment.',
      html:table(['Component','Proposed model'],[['Recurring platform','€200k+ / private network / year'],['Expansion','More participants and resource types'],['One-time work','Deployment and integration'],['Optional usage fee','Transaction or usage fee']])+note('No fixed participant increments or usage rate assumed.'),
      note:'The recurring fee is a starting point. Price expands with participant count and the number and type of resources. Deployment and integration are additional. Usage pricing is an optional later layer with no validated charging base or rate yet.'},
    {id:'A03',label:'Worked exchange example',headline:'Example: six pallets on an existing route.',
      html:table(['Participant','Operational requirement','Commercial condition'],[['Offering shipper','Lille → Paris · 8 positions','Minimum €450'],['Requesting shipper','6 pallets · before 17:00','Maximum €600'],['Existing carrier','Pickup window and detour','Permission and compensation']])+note('Illustrative proposal: 6 pallets at €520, subject to all rules and approvals.'),
      note:'This hypothetical numerical example is separate from the simplified main-scene allocation. It is not customer data. The proposed €520 sits between €450 and €600, but that does not alone prove feasibility or a benefit for every party. Route, cargo, timing, handling, detour costs and carrier compensation must also be validated.'},
    {id:'A05',label:'Why now',headline:'eFTI and transport-system integrations.',
      html:grid([['Electronic freight information','From 9 July 2027, authorities must accept information through certified eFTI platforms.'],['Data sharing','European initiatives support data sharing between transport systems.'],['Operational data','TMS, ERP and carrier data can provide inputs, with permission and integration.'],['Enlace’s task','Use approved data to allocate resources and determine terms.']]),
      note:'eFTI is a regulatory tailwind, not a universal requirement for companies to digitize and not evidence that Enlace can access their data. Actual data access, quality, integration and permission must be established for each deployment.'},
    {id:'A06',label:'Governance and confidentiality',headline:'Who can see data and approve exchanges?',
      html:grid([['Confidentiality','Each participant sees only the data they need.'],['Carrier permission','Existing contracts and explicit execution approvals.'],['Accountability','A named network operator and a record of decisions.'],['Commercial governance','Settlement rules and legal review for each network.']]),
      note:'These are design requirements, not a claim of certified compliance. Governance must define the operator, access rights, carrier authorization and commercial responsibilities. Competition-law treatment depends on the implementation and the information shared.'},
    {id:'A07',label:'Technical architecture',headline:'From offers and bids to allocations and prices.',
      html:`<div class="architecture"><div><h2>Inputs</h2><p>Offers and bids</p><p>Constraints</p><p>Permissions</p></div><div class="architecture-core"><span class="enlace-wordmark">Enlace</span><p>Feasibility + allocation</p><p>Pricing + settlement</p><p>Explanations + audit</p></div><div><h2>Outputs</h2><p>Allocation proposal</p><p>Commercial terms</p><p>Approved execution</p></div></div>`+note('Target integrations: TMS · ERP · carrier portals · operational APIs'),
      note:'This is the target architecture, not a list of completed integrations. Optimization and market design jointly determine feasible allocations and economic terms. The decision record should explain rules and approvals, while execution stays with the authorized operator and existing carriers.'},
    {id:'A08',label:'Sources',headline:'Sources and assumptions.',
      html:grid([['Eurostat · 2024','21.6% of EU road-freight vehicle-km travelled empty.'],['Fraunhofer IIS · 2023','EU30 logistics: ≈€1.6T. Transport: €816B; road share: 83%.'],['European Commission','eFTI implementation and the mobility data space.'],['Public product positioning','Transporeon, Uber Freight and collaboration research.']])+note('Pricing, network counts and rollout are proposed assumptions. Full links: SOURCES.md.'),
      note:'Sources were checked on 8 September 2026. Road spend is rounded to approximately €680 billion from €816 billion × 83%; the public summary does not substantiate a precise €681 billion. EU30 is EU27 plus UK, Norway and Switzerland. Company illustrations and pricing scenarios are not measured customer results.'},
  ];
  // Investor Q&A appendix.
  const prior=Object.fromEntries(appendix.map(s=>[s.id,s]));
  const foot=(text)=>`<p class="diligence-foot">${text}</p>`;
  const columns=(items)=>`<div class="diligence-columns">${items.map(([h,p])=>`<section><h2>${h}</h2><p>${p}</p></section>`).join('')}</div>`;
  const steps=(items)=>`<div class="diligence-steps">${items.map((p,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><p>${p}</p></div>`).join('')}</div>`;
  const compact=(heads,rows)=>table(heads,rows).replace('appendix-table','appendix-table diligence-table');
  const item=(id,label,headline,html,note='')=>({id,label,headline,html,note});
  const illustrative='Illustrative planning assumptions. No usage revenue.';
  const finance=[
    [2027,2,220,.44,-.64],[2028,6,240,1.44,-.57],[2029,15,260,3.90,0],[2030,32,285,9.12,.88],[2031,60,310,18.60,2.75],
    [2032,100,335,33.50,5.6],[2033,155,360,55.80,10.4],[2034,225,385,86.625,17.9],[2035,310,410,127.10,27.8],[2036,400,435,174,38.8]
  ];
  const chart=`<svg class="finance-chart" viewBox="0 0 1660 565" role="img" aria-label="Illustrative ARR bars and EBITDA line, 2027 to 2036, millions of euros"><g stroke="#dbe3ec">${[0,50,100,150].map(v=>`<path d="M100 ${480-v*2.3}H1600"/>`).join('')}</g><g fill="#596579" font-size="24">${[0,50,100,150].map(v=>`<text x="25" y="${488-v*2.3}">${v}</text>`).join('')}</g>${finance.map(([y,n,a,arr,e],i)=>`<rect x="${130+i*145}" y="${480-arr*2.3}" width="76" height="${arr*2.3}" rx="4" fill="#126ac0"/><text x="${168+i*145}" y="525" text-anchor="middle" fill="#596579" font-size="23">${y}</text>`).join('')}<polyline points="${finance.map((r,i)=>`${168+i*145},${480-r[4]*2.3}`).join(' ')}" fill="none" stroke="#912d68" stroke-width="8"/>${finance.map((r,i)=>`<circle cx="${168+i*145}" cy="${480-r[4]*2.3}" r="8" fill="#912d68" stroke="#fff" stroke-width="3"/>`).join('')}<text x="1100" y="35" fill="#126ac0" font-size="28">ARR €174M</text><text x="1320" y="35" fill="#912d68" font-size="28">EBITDA €38.8M</text><text x="25" y="35" fill="#596579" font-size="24">€ millions</text></svg>`;
  appendix.splice(0,appendix.length,
    item('D01','Validation','What is established. What comes next.',
      columns([['Core technology ✓','Complete'],['Design partner ✓','Agreement to start'],['First live markets →','Next validation step']])+steps(['Feasible exchanges','Net economic value','Repeated use','Willingness to pay and renew']),
      'Only core technology completion and an agreement to start with a design partner are established. No paid pilot, LOI, committed data, named customer, live revenue or renewal is asserted. Validate feasible exchanges after constraints and approvals, economic value after execution costs, repeated use, and willingness to pay or renew.'),
    item('D02','Customer economics','€200k is 0.20% of €100M in coordinated flow.',
      compact(['Improvement','Annual value','Value / fee'],[['0.5%','€500k','2.5×'],['1%','€1M','5×'],['2%','€2M','10×']])+foot('Illustrative economics. Value before platform fee and additional implementation costs.'),
      '€100M annual coordinated logistics flow is an assumed baseline, not customer evidence. Fee is €200k. Gross value-to-fee multiples are 2.5, 5 and 10; these are not net ROI. After the platform fee alone, remaining value is €300k, €800k and €1.8M. Execution, integration and change costs must also be deducted.'),
    item('D03','Collaboration evidence','Two cases where collaboration reduced cost.',
      columns([['25.83%','Transportation-cost reduction<br>Three-company Belgian case'],['$250k → $2M','Opportunity-identification investment<br>First-year savings for a U.S. lead shipper']])+foot('External case studies, not Enlace forecasts. Vanovermeire et al. (2014); Sternberg et al. (2022).'),
      'Belgian case: Vanovermeire et al., DOI 10.1080/13675567.2013.865719. The result depends on the studied coalition and delivery flexibility. U.S. FMCG case: Sternberg et al., DOI 10.1111/jscm.12278, reports $250,000 invested and $2M saved in year one. Collaboration lasted two years and savings were lower than expected. These selected historical cases establish possibility, not typical savings or an Enlace result.'),
    item('A02','Pricing model','€200k+ per private network, per year.',
      columns([['Recurring platform','More participants<br>More resource types'],['Deployment','Integration and rollout<br>Charged separately'],['Later option','Usage fee<br>Excluded from the base case']])+foot('Starting fee. No fixed price per participant assumed.'),prior.A02.note),
    item('D06','Global market size','Private logistics markets × annual platform fee.',
      `<div class="diligence-context">$12.29T global logistics costs · $3.8T global road freight</div>`+compact(['Private logistics markets','Annual fee','ARR floor'],[['500','€200k','€100M'],['2,000','€200k','€400M'],['5,000','€200k','€1B']])+foot('2024 estimates. ARR scenarios exclude expansion and usage.'),
      'Logistics costs: Armstrong & Associates, June 2026 report, 2024 estimate. Road freight: Frost & Sullivan as cited in the HKEX filing dated 27 October 2025. These separate estimates use different methods, so no road share is derived. The network-count scenarios are arithmetic, not a pipeline or forecast. Both include only recurring platform revenue.'),
    item('D07','First customer','Three conditions for the first customer.',
      columns([['Access','Can bring participants'],['Authority','Can set network rules'],['Incentive','Benefits when it works']])+foot('3PL / operator · enterprise ecosystem · committed consortium'),
      'Prioritize a sponsor that can bring compatible participants and their carriers, has authority to define governance, and has a budget owner with a measurable economic reason to run the network. The initial design partner is an agreement to start, not proof that every qualification is satisfied.'),
    item('D08','Cold start','Start with existing transport flows.',
      steps(['Historical data','Find overlapping flows','2–3 compatible shippers and existing carriers','Activate validated corridors','Keep existing procurement as fallback']),
      'Proposed launch method. Secure permission to inspect historical demand and available capacity. Test route, timing, cargo and contract fit before recruiting corridor participants. Validate compatibility through real operations; historical data alone does not guarantee future liquidity. Existing procurement remains fallback.'),
    item('D09','Infrastructure model','Customers operate networks. Enlace determines exchanges.',
      compact(['Owning one marketplace','Providing Enlace infrastructure'],[['Recruit supply and demand','Start from customer networks'],['Set marketplace rules','Customer sets participation and rules'],['Operate the intermediary','Existing providers execute'],['Focus on one market','Reuse configuration across markets']])+foot('Operating-model choice. Specific legal roles depend on contracts and jurisdiction.'),
      'This describes the intended Enlace model, not a claim that other marketplaces are limited to one resource or that software removes legal obligations. The customer operates the network; Enlace supplies configuration, allocation and pricing decisions.'),
    item('D10','What Enlace can create','Different exchanges. Powered by <span class="enlace-inline">Enlace</span>.',
      `<div class="market-configs">${[['🚛','Shared capacity'],['🤝','Procurement'],['🏭','Warehouse capacity'],['🚢 📦','Containers and ships']].map(([g,l])=>`<section><h2>${g} ${l}</h2><p>WHO + WHAT + RULES → <span class="enlace-inline">Enlace</span> → allocation + price</p></section>`).join('')}</div>`,
      'Proposed configurations, not four launched products. The initial focus is transport capacity. Each additional resource class requires its own operational model, constraints, permissions and integrations.'),
    item('D11','Network precedents','Multi-company networks can reach scale.',
      columns([['LaneHub','150+ shippers · 250 carriers<br>180k lanes · 26M matches'],['Portbase · 2025','7,200 organizations<br>€31.4M revenue<br>€630M annual added value']])+foot('External network precedents, not Enlace comparables. Uber Freight; Portbase.'),
      'LaneHub figures are historical figures reported by Uber Freight, not a current network count; matches are potential matches, not executed transactions. Portbase figures are self-reported in its 2025 annual report; added value is not platform revenue. Portbase is a port community system with a different role and business model.'),
    prior.A09,
    item('A03','Worked exchange','Six pallets: compare the alternatives.',
      compact(['','Separate procurement','Shared allocation'],[['Requester pays','€600 assumed fallback','€520 proposed price'],['Requester saves','0','€80 before other costs'],['Offering shipper receives','0 incremental revenue','€520 before execution costs']])+foot('8 positions offered · 6 needed · €450 minimum · €600 maximum. Illustrative only.'),
      'Retains the original hypothetical Lille to Paris exchange: 8 positions offered, 6 pallets needed before 17:00, supplier minimum €450, requester maximum €600, proposed price €520. The new before case assumes the requester would otherwise pay €600; this is not proven by a bid ceiling and must be checked. The offering shipper receives €520 gross, not €520 profit. Incremental handling, detour and carrier compensation remain to be deducted. €520 is €70 above the supplier minimum. Route, capacity, time and carrier approval remain mandatory.'),
    item('A05','Why now globally','Freight data standards now span modes.',
      columns([['🚛 Road','eFTI application<br>9 July 2027'],['🚢 Ocean','DCSA member commitment<br>100% eBL by 2030'],['✈️ Air','IATA ONE Record<br>Preferred standard since 2026']])+foot('Structured data supports integration. Adoption and access still vary.'),
      'European Commission: authorities must accept regulatory information through certified eFTI platforms from 9 July 2027; this is not a universal business digitization mandate. DCSA member carriers commit to 100% electronic bills of lading by 2030, an ambition rather than a universal achieved rate. IATA ONE Record became preferred data sharing standard on 1 January 2026. These do not guarantee data access or operational interoperability for Enlace.'),
    item('A06','Governance and legal role','Who controls data, decisions and execution?',
      compact(['Responsibility','Initial model'],[['Participation and rules','Network operator'],['Allocation and proposed terms','Enlace'],['Execution and approval','Existing providers and parties'],['Contracts and payment','Can remain outside Enlace']])+foot('Permissions · approval · audit · settlement. Legal review for each market.'),
      'Proposed initial allocation of responsibilities, not a legal conclusion that Enlace is never a broker or payment provider. Roles depend on actual conduct, contracts, information sharing and jurisdiction. Review competition, transport intermediation, data protection and payment obligations per deployment.'),
    item('D17','Technical moat','Reuse decision models across networks.',
      columns([['Decision models','Resource model<br>Multi-party allocation<br>Pricing and settlement'],['Configuration','Operational and commercial rules<br>Integration templates'],['Operational reuse','Permissions and audit<br>Repeatable deployment']]),
      'Potential defensibility comes from tested reusable models, integrations, rule configuration and operating knowledge. These are areas to build and demonstrate, not a claim of patents, exclusive data or an uncopyable optimizer. IP slide omitted at user request.'),
    {...prior.A07,html:prior.A07.html.replace('<h2>Inputs</h2>','<h2>Configuration + inputs</h2>').replace('<p>Offers and bids</p>','<p>Participants · resources · rules</p><p>Offers and bids</p>')},
    item('D19','Productization roadmap','Make each deployment less custom.',
      steps(['Core engine ✓','First live markets','Permissions, audit and integrations','Configurable market templates','Repeatable deployment','Second resource class']),
      'Core technology is complete as stated by the team. The remaining sequence is planned, not delivered. Seed funding is intended to reduce implementation effort through configuration, reusable integrations and market templates.'),
    item('D20','Use of funds','€2M over 24 months.',
      compact(['Use','Share','Budget'],[['Productization and integrations','35%','€700k'],['Live-market deployment','25%','€500k'],['Go to market','25%','€500k'],['Security, legal and governance','10%','€200k'],['Buffer','5%','€100k']])+foot('Proposed allocation. Total: 100% / €2M.'),
      'User-provided planning allocation, not committed expenditure. Categories allocate seed capital; they are not a detailed operating-expense forecast. Reconcile hiring and project budgets to actual deployment and sales timing.'),
    item('D21','Financial assumptions','Platform and deployment revenue only.',
      compact(['Assumption','Base case'],[['Starting price','€200k+ / private network / year'],['Average ARR / network','€220k (2027) → €310k (2031) → €435k (2036)'],['Deployment fee','€50k per new network'],['Gross margin','55% (2027) → 79% (2031)'],['Usage revenue','€0']])+foot('Planning assumptions. Expansion comes from participants and resources.'),
      'Markets at year-end: 2, 6, 15, 32, 60 for 2027–2031. No churn is explicitly modeled: this is optimistic and must be stress-tested. Recognized revenue equals the average of opening and closing ARR plus €50k per new network, assuming uniform go-live timing and linear expansion. Gross margins are total margins, including deployment. Benchmarkit 2025 reports median subscription gross margin 81%, total 77%, services 30%; these are external benchmarks, not Enlace results. Bessemer enterprise CAC payback under 24 months is a future guardrail, not a measured metric.'),
    item('D22','Five-year cash flow','€2M funds five years of deployment.',
      compact(['€M unless stated','2027','2028','2029','2030','2031'],[['Live markets, year-end','2','6','15','32','60'],['Year-end ARR','0.44','1.44','3.90','9.12','18.60'],['Recognized revenue','0.32','1.14','3.12','7.36','15.26'],['Gross margin','55%','65%','72%','76%','79%'],['EBITDA','-0.64','-0.57','0.00','0.88','2.75'],['Capex','-0.05','-0.08','-0.12','-0.20','-0.30'],['Approx. net cash flow','-0.69','-0.65','-0.12','0.68','2.45'],['Seed financing','2.00','0','0','0','0'],['Closing cash','1.31','0.66','0.54','1.22','3.67']])+foot('Excludes working-capital timing, tax, financing costs and future rounds.'),
      'Seed assumed available at the start of 2027; opening cash assumed zero. EBITDA is a planning input. Cash flow approximates EBITDA less capex. Displayed values use the provided rounded base case. Revenue 2030 exact is €7.36M. Gross profit less EBITDA implies operating expenses €0.816M, €1.311M, €2.2464M, €4.7136M and €9.3054M. Lowest displayed year-end cash is €0.54M in 2029. This does not prove intra-year liquidity or that €2M is sufficient if sales, collections or gross margins miss plan.'),
    item('D23','Ten-year scaling','400 markets × €435k = €174M ARR.',chart+foot('Scaling model, not management guidance. No usage revenue.'),
      'Detailed model (year / live markets / average ARR in €k / ARR in €M / EBITDA in €M): '+finance.map(r=>r.join(' / ')).join('; ')+'. 2036 recognized revenue assumption: average of €127.1M and €174M ARR plus 90 deployments × €50k = €155.05M. €38.8M EBITDA divided by €155.05M recognized revenue is 25.0%. EBITDA margin must not be calculated using year-end ARR. The ten-year model is a scenario, not evidence of achievable demand.'),
    item('D24','Sensitivity','2031: networks × annual recurring revenue.',
      compact(['Scenario','Live networks','ARR / network','ARR'],[['Downside','30','€250k','€7.5M'],['Base','60','€310k','€18.6M'],['Upside','100','€350k','€35M']])+foot('Slower conversion may require lower hiring or additional financing.'),
      'These scenarios vary only market count and average ARR. They are not complete cash-flow scenarios. A six-month sales delay can materially change recognized revenue and collections; no precise downside cash runway is asserted without a monthly model.'),
    item('D25','Key risks','Five risks to test early.',
      compact(['Risk','Response'],[['Insufficient liquidity','Validate corridor overlap before launch'],['Trust and data access','Permissions, limited disclosure and audit'],['Custom-project trap','Templates and repeatable integrations'],['Enterprise sales cycle','Stage hiring against signed deployments'],['Regulation and governance','Review legal roles in each market']]),
      'Proposed mitigations reduce risk but do not eliminate it. Track exchange completion and frequency, permission and onboarding friction, implementation hours, sales conversion and contract-cycle duration, plus legal constraints per jurisdiction.'),
    item('A08','Sources','External evidence and Enlace assumptions.',
      `<div class="diligence-sources"><section><h2>External evidence</h2><p>Armstrong & Associates · Frost & Sullivan / HKEX<br>Vanovermeire et al. · Sternberg et al.<br>Uber Freight / LaneHub · Portbase<br>European Commission · DCSA · IATA<br>Benchmarkit · Bessemer</p></section><section><h2>Enlace assumptions</h2><p>€200k+ starting fee · €50k deployment<br>Market counts · expansion · margins<br>€2M allocation · cash-flow scenarios</p></section></div>`+foot('Full references and model calculations: SOURCES.md and FINANCIAL-MODEL.md.'),
      'Sources: https://www.3plogistics.com/wp-content/uploads/2026/06/Third-Party_Logistics_Market_Results_and_Trends_2026_5JUN2026.pdf ; https://www1.hkexnews.hk/app/sehk/2025/107809/documents/sehk25102701615.pdf ; https://doi.org/10.1080/13675567.2013.865719 ; https://doi.org/10.1111/jscm.12278 ; https://www.uberfreight.com/en-US/blog/increasing-shipper-carrier-collaboration-with-transplaces-planned-continuous-moves-lanehub-platform ; https://www.portbase.com/en/annual-reports/annual-report-2025/ ; https://transport.ec.europa.eu/transport-themes/logistics-and-multimodal-transport/efti-regulation_en ; https://dcsa.org/get-involved/100-percent-ebl ; https://www.iata.org/en/pressroom/2026-releases/2026-03-10-01/ ; https://www.benchmarkit.ai/2025benchmarks ; https://www.bvp.com/assets/uploads/2024/04/From-Start-to-Centaur-The-founders-roadmap-to-100-million-ARR-Bessemer-Books-Edition-040924.pdf . Full URLs and scope qualifications are recorded in SOURCES.md. Detailed arithmetic and machine-readable model data are in FINANCIAL-MODEL.md and output/data/financial-model.json. External studies are not Enlace forecasts. IP slide omitted at the user’s request.')
  );

  // Keep the requested investor follow-up topics only.
  const retainedTopics = new Set(['D06','D20','D22','D23','D25','A08']);
  appendix.splice(0, appendix.length, ...appendix.filter(s => retainedTopics.has(s.id)));
  for (const slide of appendix) {
    slide.html = slide.html.replace(/<p class="(?:diligence-foot|appendix-foot)">[^<]*[Ii]llustrative[^<]*<\/p>/g, '');
    slide.headline = slide.headline.replace(/illustrative/ig, '').replace(/\s{2,}/g, ' ').trim();
  }
  const marketSize = appendix.find(s => s.id === 'D06');
  marketSize.html = marketSize.html.replace(/<div class="diligence-context">[\s\S]*?<\/div>/, '')
    .replace('</table>', '</table><p class="network-fee-rationale">€200k+ reflects the cost of replacing a specialized internal team and serves an entire multi-company network.</p>');

  appendix.unshift({id:'A00',label:'Contents',headline:'Appendix',html:`<div class="appendix-contents">${appendix.map((item,i)=>`<button data-appendix-target="${item.id}"><span>${String(i+1).padStart(2,'0')}</span>${item.label}</button>`).join('')}</div>`,note:'Select a topic, or advance through the appendix with the arrow keys. Press A to return to the main pitch.'});
  let previous=0;
  const main=scenes.flatMap(s=>s.holds.map((h,beatIndex)=>{
    const hold={...h,sceneId:s.id,sceneNumber:s.number,sceneLabel:s.label,beatIndex,beatCount:s.holds.length,chapter:s.chapter,entry:h.id==='TITLE'?0:Number((previous+.05).toFixed(2)),advance:Number((h.time-previous).toFixed(2))};
    previous=h.time;return hold;
  }));
  appendix.forEach((s,i)=>{s.chapter='Appendix';s.start=Number((previous+.05).toFixed(2));s.time=Number((s.start+2).toFixed(2));s.end=s.time;s.entry=s.start;s.advance=Number((s.time-previous).toFixed(2));s.sceneNumber=i+1;s.beatCount=1;s.beatIndex=0;previous=s.time;});
  window.ENLACE_DECK={scenes,main,appendix,duration:Math.ceil(previous+1),times:[...main,...appendix].map(h=>h.time)};
})();
